# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot = {
    initrd = {
      availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
      kernelModules = [ ];
    };
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/6b47e646-e650-485d-a0ad-2feb337506e4";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/FB64-FC11";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

    "/home" = {
      device = "/dev/disk/by-uuid/e2d9c427-977c-4271-ae93-88e11cedb227";
      fsType = "ext4";
    };

    "/steam" = {
      device = "/dev/disk/by-uuid/249c8bec-3ec2-4b89-8618-748cd918d4ba";
      fsType = "btrfs";
      options = [
        "space_cache=v2"
        "discard=async"
      ];
    };

    # "/home/zozano/.var" = {
    #   device = "/dev/disk/by-uuid/249c8bec-3ec2-4b89-8618-748cd918d4ba";
    #   fsType = "btrfs";
    #   options = [
    #     "subvol=@var"
    #     "space_cache=v2"
    #     "discard=async"
    #     "nofail"
    #   ];
    # };

    # "/home/zozano/.var/app/moe.launcher.honkers-launcher" = {
    #   device = "/dev/disk/by-uuid/249c8bec-3ec2-4b89-8618-748cd918d4ba";
    #   fsType = "btrfs";
    #   options = [
    #     "subvol=@honkai-impact"
    #     "space_cache=v2"
    #     "discard=async"
    #     "nofail"
    #   ];
    # };

    "/home/zozano/.var/app/moe.launcher.the-honkers-railway-launcher" = {
      device = "/dev/disk/by-uuid/249c8bec-3ec2-4b89-8618-748cd918d4ba";
      fsType = "btrfs";
      options = [
        "subvol=@star-rail"
        "space_cache=v2"
        "discard=async"
        "nofail"
      ];
    };

    "/home/zozano/.local/share/Steam" = {
      device = "/dev/disk/by-uuid/249c8bec-3ec2-4b89-8618-748cd918d4ba";
      fsType = "btrfs";
      options = [
        "subvol=@steam"
        "space_cache=v2"
        "discard=async"
        "nofail"
      ];
    };

    "/home/zozano/.bitmonero" = {
      device = "/dev/disk/by-uuid/249c8bec-3ec2-4b89-8618-748cd918d4ba";
      fsType = "btrfs";
      options = [
        "subvol=@monero"
        "space_cache=v2"
        "discard=async"
        "nofail"
      ];
    };

    "/server" = {
      device = "z-home@192.168.1.157:/";
      fsType = "sshfs";
      options = [ 
        "nodev"
        "nofail"
        "allow_other"
        "IdentityFile=/root/.ssh/home-server_z-nix"
        "x-systemd.automount"
        "x-systemd.requires=network-online.target"
      ];
    };
    "/data" = {
      device = "z-home@192.168.1.157:/data";
      fsType = "sshfs";
      options = [
        "nodev"
        "nofail"
        "allow_other"
        "IdentityFile=/root/.ssh/home-server_z-nix"
        "x-systemd.automount"
        "x-systemd.requires=network-online.target"
      ];
    };
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp10s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp9s0.useDHCP = lib.mkDefault true;

  swapDevices = [ { label = "swap"; } ];
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  system.stateVersion = "24.05"; # never delete this, unless you want your shit pushed in.
}
