# Auto-generated using compose2nix v0.3.1.
{
  pkgs,
  lib,
  ...
}: {
  environment.systemPackages = with pkgs; [
    libva-utils
    nvidia-container-toolkit
  ];

  hardware.nvidia-container-toolkit.enable = true;

  networking.firewall.interfaces."podman+".allowedUDPPorts = [53];

  virtualisation = {
    podman = {
      enable = true;
      autoPrune.enable = true;
      dockerCompat = true;
      defaultNetwork.settings.dns_enabled = true;
    };

    oci-containers = {
      backend = "podman";
      containers."tdarr-node" = {
        image = "ghcr.io/haveagitgat/tdarr_node:latest";

        environment = {
          "NVIDIA_DRIVER_CAPABILITIES" = "all";
          "NVIDIA_VISIBLE_DEVICES" = "all";
          "TZ" = "Australia/Sydney";
          "nodeID" = "MyNode-5600G";
          "serverIP" = "192.168.1.157";
          "serverPort" = "8266";
        };
        volumes = [
          "/var/lib/tdarr-node/configs:/app/configs:rw"
          "/var/lib/tdarr-node/logs:/app/logs:rw"
          "/var/lib/tdarr-node/transcode:/app/temp:rw"
          "/data/media:/media:rw"
          "/dev/dri:/dev/dri:rw"
        ];
        log-driver = "journald";
        extraOptions = [
          "--device=/dev/dri:/dev/dri:rwm"
          "--device=nvidia.com/gpu=all"
          "--network-alias=tdarr-node"
          "--network=tdarr_default"
          "--group-add=video"
          "--label=io.containers.autoupdate=registry"
        ];
      };
    };
  };

  systemd.services = {
    "podman-tdarr-node" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      unitConfig.RequiresMountsFor = "/data/media";
      bindsTo = ["data.mount"];

      after = [
        "podman-network-tdarr_default.service"
      ];
      requires = [
        "podman-network-tdarr_default.service"
      ];
      partOf = [
        "data.mount"
        "podman-compose-tdarr-root.target"
      ];
      wantedBy = [
        "podman-compose-tdarr-root.target"
      ];
    };

    "podman-network-tdarr_default" = {
      path = [pkgs.podman];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "podman network rm -f tdarr_default";
      };
      script = ''
        podman network inspect tdarr_default || podman network create tdarr_default
      '';
      partOf = ["podman-compose-tdarr-root.target"];
      wantedBy = ["podman-compose-tdarr-root.target"];
    };
  };

  systemd.targets."podman-compose-tdarr-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };

  systemd.timers."podman-auto-update".wantedBy = ["timers.target"];

  systemd.timers."podman-auto-update".timerConfig = {
    OnCalendar = lib.mkForce "hourly";
    RandomizedDelaySec = "5m";
    Persistent = true;
  };
}
