# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
   environment.systemPackages = with pkgs; [
      libva-utils
      nvidia-container-toolkit
   ];

   hardware.nvidia-container-toolkit.enable = true;

  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };

  # Enable container name DNS for non-default Podman networks.
  # https://github.com/NixOS/nixpkgs/issues/226365
  networking.firewall.interfaces."podman+".allowedUDPPorts = [ 53 ];

  virtualisation.oci-containers.backend = "podman";

  # Containers
  # virtualisation.oci-containers.containers."tdarr" = {
  #   image = "ghcr.io/haveagitgat/tdarr:latest";
  #   environment = {
  #     "NVIDIA_DRIVER_CAPABILITIES" = "all";
  #     "NVIDIA_VISIBLE_DEVICES" = "all";
  #     "TZ" = "Australia/Sydney";
  #     "serverIP" = "0.0.0.0";
  #     "serverPort" = "8266";
  #   };
  #   volumes = [
  #     "/docker/tdarr/configs:/app/configs:rw"
  #     "/docker/tdarr/logs:/app/logs:rw"
  #     "/docker/tdarr/server:/app/server:rw"
  #     "/docker/tdarr/transcode:/temp:rw"
  #     "/data/media/shows:/shows:rw"
  #     "/data/media/movies:/movies:rw"
  #     "/dev/dri:/dev/dri:rw"
  #   ];
  #   ports = [
  #     "8265:8265/tcp"
  #     "8266:8266/tcp"
  #   ];
  #   log-driver = "journald";
  #   extraOptions = [
  #     "--device=/dev/dri:/dev/dri:rwm"
  #     "--device=nvidia.com/gpu=all"
  #     "--network-alias=tdarr"
  #     "--network=tdarr_default"
  #   ];
  # };
  # systemd.services."podman-tdarr" = {
  #   serviceConfig = {
  #     Restart = lib.mkOverride 90 "always";
  #   };
  #   after = [
  #     "podman-network-tdarr_default.service"
  #   ];
  #   requires = [
  #     "podman-network-tdarr_default.service"
  #   ];
  #   partOf = [
  #     "podman-compose-tdarr-root.target"
  #   ];
  #   wantedBy = [
  #     "podman-compose-tdarr-root.target"
  #   ];
  # };
  virtualisation.oci-containers.containers."tdarr-node" = {
    image = "ghcr.io/haveagitgat/tdarr_node:latest";
    environment = {
      "NVIDIA_DRIVER_CAPABILITIES" = "all";
      "NVIDIA_VISIBLE_DEVICES" = "all";
      "TZ" = "Australia/Sydney";
      "nodeID" = "MyNode-5600G";
      "serverIP" = "192.168.1.157";
      "serverPort" = "8266";
    };
    volumes = [
      "/var/lib/tdarr-node/configs:/app/configs:rw"
      "/var/lib/tdarr-node/logs:/app/logs:rw"
      "/var/lib/tdarr-node/transcode:/app/temp:rw"
      "/data/media:/data/media:rw"
      "/dev/dri:/dev/dri:rw"
    ];
    # dependsOn = [
    #   "tdarr"
    # ];
    log-driver = "journald";
    extraOptions = [
      "--device=/dev/dri:/dev/dri:rwm"
      "--device=nvidia.com/gpu=all"
      "--network-alias=tdarr-node"
      "--network=tdarr_default"
    ];
  };
  systemd.services."podman-tdarr-node" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-tdarr_default.service"
    ];
    requires = [
      "podman-network-tdarr_default.service"
    ];
    partOf = [
      "podman-compose-tdarr-root.target"
    ];
    wantedBy = [
      "podman-compose-tdarr-root.target"
    ];
  };

  systemd.services."podman-network-tdarr_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f tdarr_default";
    };
    script = ''
      podman network inspect tdarr_default || podman network create tdarr_default
    '';
    partOf = [ "podman-compose-tdarr-root.target" ];
    wantedBy = [ "podman-compose-tdarr-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-tdarr-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
  }
