zozano@z-nixos ~/.d/z/modules (main) [SIGINT]> cat tdarr.nix 
# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };

  # Enable container name DNS for non-default Podman networks.
  # https://github.com/NixOS/nixpkgs/issues/226365
  networking.firewall.interfaces."podman+".allowedUDPPorts = [ 53 ];

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."tdarr" = {
    image = "ghcr.io/haveagitgat/tdarr:latest";
    environment = {
      "NVIDIA_DRIVER_CAPABILITIES" = "all";
      "NVIDIA_VISIBLE_DEVICES" = "all";
      "PGID" = "100";
      "PUID" = "1000";
      "TZ" = "Australia/Sydney";
      "UMASK_SET" = "002";
      "ffmpegVersion" = "7";
      "inContainer" = "true";
      "internalNode" = "true";
      "nodeName" = "MyInternalNode";
      "serverIP" = "0.0.0.0";
      "serverPort" = "8266";
      "webUIPort" = "8265";
    };
    volumes = [
      "/docker/tdarr/configs:/app/configs:rw"
      "/docker/tdarr/logs:/app/logs:rw"
      "/docker/tdarr/server:/app/server:rw"
      "/docker/tdarr/transcode:/temp:rw"
      "/server/data/media:/media:rw"
    ];
    ports = [
      "8265:8265/tcp"
      "8266:8266/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--device=/dev/dri:/dev/dri:rwm"
      "--device=nvidia.com/gpu=all"
      "--network-alias=tdarr"
      "--network=bridge"
    ];
  };
  systemd.services."podman-tdarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-tdarr-root.target"
    ];
    wantedBy = [
      "podman-compose-tdarr-root.target"
    ];
  };
  virtualisation.oci-containers.containers."tdarr-node" = {
    image = "ghcr.io/haveagitgat/tdarr_node:latest";
    environment = {
      "NVIDIA_DRIVER_CAPABILITIES" = "all";
      "NVIDIA_VISIBLE_DEVICES" = "all";
      "PGID" = "100";
      "PUID" = "1000";
      "TZ" = "Australia/Sydney";
      "UMASK_SET" = "002";
      "ffmpegVersion" = "7";
      "inContainer" = "true";
      "nodeName" = "MyExternalNode";
      "serverIP" = "0.0.0.0";
      "serverPort" = "8266";
    };
    volumes = [
      "/docker/tdarr/configs:/app/configs:rw"
      "/docker/tdarr/logs:/app/logs:rw"
      "/docker/tdarr/transcode:/temp:rw"
      "/server/data/media:/media:rw"
    ];
    dependsOn = [
      "tdarr"
    ];
    log-driver = "journald";
    extraOptions = [
      "--device=/dev/dri:/dev/dri:rwm"
      "--device=nvidia.com/gpu=all"
      "--network=container:tdarr"
    ];
  };
  systemd.services."podman-tdarr-node" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-tdarr-root.target"
    ];
    wantedBy = [
      "podman-compose-tdarr-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-tdarr-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
